version: '3.8'

services:
  php:
    image: php:8.1-cli
    container_name: php-container
    volumes:
      - .:/var/www/html/tests/tests.php
    networks:
      - app-network
    command: php -S 0.0.0.0:8000 -t /var/www/html

  db:
    image: mysql:5.7
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    networks:
      - app-network
    ports:
      - '3306:3306'

networks:
  app-network:
    driver: bridge
