name: Run PHP Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 4: Build and run Docker containers using Docker Compose
      - name: Build and run Docker containers
        run: |
          docker-compose up -d

      # Step 5: Run PHP tests inside the container
      - name: Run PHP Tests
        run: |
          docker-compose exec -T php php /path/to/tests.php

      # Step 6: Stop Docker containers after testing
      - name: Stop Docker containers
        run: |
          docker-compose down
